Azure/azure-xplat-cli

test/commands/cli.storage.blob-tests.js, test/recordings/cli.storage.blob-tests.nock.js
As we met "Error: timeout of 500000ms exceeded" from time to time which was caused by stream issue in nodejs 0.8. So I disable the cases until we update storage nodejs SDK to 0.4.3.
=> Disable blob cases for pending investigation for failures on node 0.8

lib/commands/asm/vm._js
Modify the help message for the default docker certs dir from .docker/ to ~/.docker/   
MacBook-Pro:asm willy$ azure vm docker create -h
help:    Create a VM 
help:    
help:    Usage: vm docker create [options] <dns-name> <image> <user-name> [password]
help:    
help:    Options:
help:      -h, --help                             output usage information
help:      -v, --verbose                          use verbose output
help:      --json                                 use json output
help:      -p, --docker-port [port]               Port to use for docker [4243]
help:      -C, --docker-cert-dir [dir]            Directory containing docker certs [.docker/]
MacBook-Pro:asm willy$ azure vm docker create -h
help:    Create a VM 
help:    
help:    Usage: vm docker create [options] …
=> correct the help message for the default docker cert path

test/commands/cli.site.deploymentscript-tests.js
We will need to fix it. It makes test run longer and the log is unreadable.
The root cause is on the kuduscript package, which one negative test hits a streamline bug from it.
The fix for the package owner is to migrate streamline dependency to the latest version which contains the fix See https://github.com/Sage/streamlinejs/issues/242
=> Fix for massive verbose output during test run (repro'd only on node 0.12.0)

tools/windows/build.cmd, tools/windows/scripts/prepareRepoClone.cmd
1. Check errorlevel correctly, what we have now is not correct. 
2. Checkout exit code of each step consistently, including node.exe and robocopy.exe
3. Stop the script if there are any errors, and do not continue
4. Check folder exists before delete, and doing this will get rid of all those output of "file doesn't exist"
5. set codepage, so "npm install" works consistently
=> Improve the windows installer script  

lib/commands/asm/iaas/image.js, test/commands/cli.vm.image-tests.js
```
azure vm image show --json 2b171e93f07c4903bcad35bda10acf22__CoreOS-Beta-584.0.0
{
"category": "Public",
"label": "CoreOS Beta",
"location": [
"East Asia",
"Southeast Asia",
"North Europe",
"West Europe",
"Central US",
"East US",
"East US 2",
"North Central US",
"South Central US",
"West US"
],
"logicalSizeInGB": 31,
"name": "2b171e93f07c4903bcad35bda10acf22__CoreOS-Beta-584.0.0",
"operatingSystemType": "Linux",
"description": "The Beta channel consists of promoted Alpha releases. Mix a few Beta machines into your production clusters to catch any bugs specific to your hardware or configu
ration.",
"imageFamily": "CoreOS Beta",
"publishedDate": "2015-02-18T00:00:00.000Z",
"isPremium": false,
"iconUri": "coreos-globe-color-lg-100px.png",
"recommendedVMSize": "Medium",
"publisherName": …
```
=> modified the location property to be an array from a ";" sep. string

test/testlistarm.txt
failed twice in a row with error like: https://magnum.travis-ci.com/Azure/azure-sdk-for-node-pr/jobs/16458930. 
This is impacting the release for //Build. Will open PBI to track
=> disable unreliable api package suite

lib/commands/asm/hdinsight._js
List of bugs fixed in this change. 
1. Xplat-CLI tool failed to create Linux cluster, Error "Version '3.2' is not available in Azure region '"East US 2"'."
2. XPlat-CLI failed to create windows cluster. Error: "VM size is not allowed for the specified cluster"
3. XPlat-CLI shows succeeded to create linux cluster but actually failed. error "DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'UserPassword for Linux OS Profile must be 6-72 characters long and meet complexity requirements'"
4. XPlat-CLI shows succeeded but actually failed to create linux cluster: "DeploymentDocument 'AmbariConfiguration_1_7' failed the validation. Error: 'The password set in Ambari configuration default_password field must meet Azure password policy'"
5. XPlat-CLI failed to create linux …
=> Bug fix for hdinsight cluster management commands.

lib/commands/arm/apiapp/lib/dirops.js
A partner team reported failure to build packages when the package source was on a unc share. Turns out there's a bug in node 0.10.23's path module when the source directory is a full unc path. This fix works around the bug.
=> Work around packaging failure on node 0.10.23 from unc path

lib/util/utils.js, package.json
Move events client out of azure rollup into its own azure-monitoring. This will also fix a bug with "caller" field missing for group log commands using the old monitoring sdk
=> Move events client out of azure rollup into its own azure-monitoring

test/testlistarm.txt
the list operation in the test setup is not right
=> disable group template testss, because the recorded nock file is not correct

ChangeLog.txt, lib/commands/asm/vm._js, lib/commands/asm/vm/vmclient.js
Introduced new option `--delete-chef-config` for azure vm extension set-chef command.
`--delete-chef-config` is useful in uninstall/update extension process to decide whether to keep chef config on VM.
=> Changes to add deleteChefConfig option for set chef extension command

tools/windows/scripts/prepareRepoClone.cmd
Otherwise some files will have a too long absolute path.
=> Add a few more packages to list of removing azure-common dependency module

tools/osx-setup/scripts/azure, tools/osx-setup/scripts/createTarball.sh, tools/windows/scripts/prepareRepoClone.cmd
we need to regenerate because the installer will  pre-compile streamline files so that the file extension needs to be refreshed from '._js' to '.js' in the metadata
=> add script to regenerate metadata files during build installer

test/commands/arm/apiapp/arm.apiapp-tests.js, test/commands/arm/apiapp/lib/deployLib-tests.js
Mocked out setTimeout so that it's not waiting five seconds per poll even when running mocked.
=> Speed improvement when running apiapp tests mocked

test/commands/arm/webapp/arm.webapp.feature-tests.js
Don't access current profile till suite gets set up. Otherwise, the test will hit exception of no existing accounts
=> Address a test flakiness in webapp command

lib/util/profile/environment.js, lib/util/profile/subscriptionUtils.js
this is a temp fix. The good fix, which would happen shortly in dev branch, would be refactor the environment.js and do not use the "accessToken" field naming, which really means an authentication context
=> fix login as service principal

test/data/imageUrn.json
There is a known issue where we are trying to set extension and it throws error on windows 2008 offers. Refering tracking bug in here https://github.com/MSOpenTech/azure-xplat-cli/issues/368. This test data is corrected to have windows 2012 offers where extension set works correctly.
=> Corrected test data for extension test

lib/commands/arm/apiapp/apiapp._js
Fixes issue with "apiapp create" when you don't give the -u switch.
=> Fix for creating apiapps without package id

lib/commands/asm/vm._js
The --remote-subnet option is missing from commander settings.
=> add --remote-subnet option for setting acl-rule

test/framework/test-logger.js
Fix bug where create logging file would fail because mkdir method was not synchronous.
- Log directory would not be created in time on a slower computer, causing the log file creation to throw a 'file does not exist' error.
=> Fix bug in creating log directory

test/commands/arm/keyvault/arm.keyvault-tests.js, test/recordings/arm-cli-keyvault-tests/suite.arm-cli-keyvault-tests.nock.js
Add optional environment variable AZURE_ARM_TEST_RESOURCE_GROUP in keyvault tests to specify resource group.
- Currently no other tests use the AZURE_ARM_TEST_RESOURCE_GROUP variable.
=> Add optional environment to specify resource group.

tools/windows/scripts/deleteTokens.cmd, tools/windows/scripts/listTokens.cmd
Simple wraps around cred.exe which has pretty hard-to-remember target filter formats
=> 2 util commands to help people diagnose cli access token storage issues

package.json, tools/windows/scripts/deleteTokens.cmd, tools/windows/scripts/listTokens.cmd
This will leverage recent version update on sdk lib of using ^ on common dependency. The positive consequence is we will have less different version of azure-common scattered under "node_modules"
=> update the azure-common version

test/testlist.txt
Disabling cli.mobile.migration-tests as we do not want it to be run by automation (instability, static mobile service names, occasional environment cleanup required).  We run monthly disaster recovery tests which test this command.
=> Disabling DR test in automated runs

lib/commands/asm/vm/vmclient.js
WALinuxAgent currently disables SSH password authentication by default
unless provisioning data explicitely sets DisableSshPasswordAuthentication
to false.  This patch triggers adding DisableSshPasswordAuthentication
element when either --ssh or --no-ssh-endpoint is given.  Value is set
to false by default and true when --no-ssh-password is given.
See also #1601, #1625 and #1667.
=> Keep password authentication if --ssh or --no-ssh-endpoint is given.

lib/cli.js, lib/commands/help.js, test/commands/cli.help-tests.js, test/testlist.txt
fix https://github.com/Azure/azure-xplat-cli/issues/1915
Also I tweaked the code to get the help from the metadata file rather loading the command file. This should get several seconds of perf improvement
=> Make "help <command>" work

lib/cli.js, lib/util/logging.js, lib/util/sillyTransport.js, test/framework/cli-executor.js, test/framework/test-logger.js
Added a new winston transport to buffer silly logs in memory & write them to azure.details.err in the event of a cli command failure.
Upon a mocha test failure the silly log for that test will be written into the test output file for that run.
I also added a check for AZURE_CLI_APPEND_LOGS environment variable, which when true will append to azure.err & azure.details.err instead of overwrite.  This can be useful if a client is experiencing problems using a script which calls multiple cli commands.
=> Added silly log report upon CLI failures

package.json
npm starts to push for this since 2.10.0, so we follow. 
(https://github.com/npm/npm/releases/tag/v2.10.0)
=> fix #1923 (use SPDX for license expression)

test/commands/arm/group/arm.group.deployment-tests.js
My previous PR https://github.com/Azure/azure-xplat-cli/pull/1983 didn't include this change, which should have been included. This is the test that validates the "outputs" after group deployment create
=> Edit group deployment test to validate outputs

package.json
This version includes update on http proxy. With this change, adal-node will pick up this new version through its use of sliding version, and proxies will be respected when acquire tokens.
=> upgrade request version to 2.52.0

lib/commands/arm/network/constants._js
This PR contains minor fix and brings support for `None` next hop type for Route in ARM
https://github.com/MSOpenTech/azure-xplat-cli/issues/433 fixed
=> ARM RouteTable Route: add support for 'None' next hop type

tools/osx-setup/build.sh, tools/windows/scripts/prepareRepoClone.cmd
we have to now, because the 0.9.6 installer included 0.12.7 through local script tweak, if we still use 0.10.23, the windows installer will be broken under upgrade scenario
=> make installer use node v0.12.7

lib/util/authentication/osx-keychain.js, lib/util/authentication/osx-token-storage.js
Those bad entries were the leftovers by the issus #1958
=> [cli-osx]: get account clear work with bad service principal items cached in the keychain

lib/cli.js, test/commands/arm/rediscache/arm.rediscache-tests.js, test/commands/cli-auto-complete.tests.js, test/commands/cli.mobile.table-tests.js, test/framework/cli-test.js, test/testlist.txt
When the test run finishes, test framework will always dump out the error to the console. So nothing gets lost
This PR mainly gets rid of the useless errors produced by negative tests.
=> Clean up test run output by not emitting out errors to the console

.gitignore, package.json, scripts/unit.js
Use Istanbul. 
Run it on AAD login related code which contains the highest number of incoming bugs
=> wire up code coverage npm task

lib/commands/asm/network/virtualNetwork._js
the command network vnet delete network-name does not work when there is only one existing network
=> fix network vnet delete when there is only one network

lib/commands/arm/role/roleAssignments._js
If both upn and --includeClassicAdmins options have been provided, the list of classic admins should be filtered by the given user principal.
=> Authorization:bug fix in role assignment list to filter classic admins if user principal has been provided

package.json
To fix the scenario breakings with Nodejs 4.x and io.js.
=> Update the storage dependency to 0.6.0 to be compatible with Nodejs 4.x

lib/cli.js, lib/util/logging.js, lib/util/sillyTransport.js, test/framework/cli-executor.js
Added truncation by default to the silly log capture after 1MB of logs has been captured.
Added a AZURE_CLI_DISABLE_LOG_CAPTURE environment variable which allows silly log capturing to be disabled.
=> Silly Log Truncation

lib/util/authentication/adalAuthForUser.js
Using "es-mx" is not a valid value. Once AAD server fixes the bug at its end, it will interpret as Spanish language and start to offer response in that language.
=> do not set language parameter when invoke adal-node for user code 

lib/commands/asm/network/nsg._js
This PR includes minor fix for `azure nsg rule create` command in `ASM` and brings port-range support for `--source-port-range` and `--destination-port-range` options, related https://github.com/Azure/azure-xplat-cli/issues/2177 issue fixed
@yugangw-msft can this be merged to `release-0.9.10` branch?
=> ASM: NSG Rule create command fixed

lib/commands/arm/group/group.deployment._js, lib/commands/arm/group/groupUtils._js, lib/plugins.arm.json
The Azure API apparently prevents some roles (e.g. VM contributor) from
validating deployments, even when they can perfectly execute them. This patch
simply adds an options the supresses the deployment validation step to work
around this problem.
=> Add an option to avoid deployment validation

lib/util/authentication/win-token-storage.js
Till now azure-cli just silently swallows any error on removing, which is sort of bad, because old tokens will likely fail adal later for multiple token matches and 'azure login' will get stuck. So let us surface it and at least we will know what was the real error.
=> Surface the error when azure-cli fails to remove token from windows secure storage

lib/commands/arm/ad/adUtils._js, lib/commands/arm/role/roleAssignments._js, package.json
This will also search for object ids in the partner tenant (artemis/CSP scenario)
=> Graph: Add the includeDirectoryObjectReferences flag to the GetObjectsByObjectIds call 

cli.njsproj, lib/util/utilsCore.js, package.json, scripts/warn-existing-streamline-files.js
This is to workaround possible stale streamline precompiled files, whose fix could take a while to sort out.
=> Put a warning on existing streamline files

lib/commands/arm/datalakeanalytics/datalakeanalytics._js, lib/commands/arm/datalakeanalytics/datalakeanalytics.utils.js, lib/commands/arm/datalakestore/datalakeStore._js, lib/commands/arm/datalakestore/datalakeStore.utils.js, lib/plugins.arm.json
remove 'tags' from help and syntax, which resulted in parsing issues
when generating the commands.
Account creation is now functional again and tags show up properly under
options.
Also missed a couple datalake -> datalakestore renames, those are now included.
Finally, made --force and --folder actual switches, instead of having them require a value.
=> Fix for account creation and a couple renames

lib/commands/arm/datalakeanalytics/datalakeanalytics._js, lib/commands/arm/datalakestore/datalakeStore._js, lib/plugins.arm.json, package.json
This fixes the following:
Help text for required usage
Account Creation
Adding/removing data sources
Proper casing for status properties
Including callbacks where necessary
replacing 'delete' with deleteMethod (delete is reserved)
Including help text for upload/download to indicate that only text files
are supported
Allow creation of empty files
Ensure jobs can be submitted in a file as UTF8 format (currently only
supported) format.
=> Fixes to DataLake* cli commands

lib/commands/arm/network/expressRoute._js
Minor fix for https://github.com/Azure/azure-xplat-cli/issues/2281 issue
=> ARM: 'network express-route provider list' now outputs comma separated bandwidth

lib/util/profile/environment.js
graph url should point to the China instance of graph, not public.
This causes tokens from the issuer to be invalid when presented to graph.
=> Fix graph url endpoint for AzureChinaCloud environment

.gitignore, tools/osx-setup/scripts/createTarball.sh, tools/windows/scripts/prepareRepoClone.cmd
There are useless as compiled *.js stay right beside
=> remove useless ._js file before create installer so to shrink the download size

lib/util/patch-winston.js
"fs.writeSync" doesn't guarantee all data will be written into the pipe; rather it returns the number of bytes written, which azure-cli code just ignores. This error doesn't surface on windows or with old node versions(<=0.12.x), but our bug regardless. 
There are several options, and this PR picks the most straightforward one.
=> Fix #2285: truncated command json output during piping

lib/util/utils.js
This looks like it has been introduced by mistake in: https://github.com/Azure/azure-xplat-cli/commit/b1c23942cd12df3e279ffea7338fff79a401ff13#diff-0261004ab0f5706809fa8fe41a29f27aL118 
when it was moved from `lib/util/profile/subscription.js` to `lib/util/utils.js` where the value of `utils` was valid in `subscription.js`
=> Correct variable declaration in creating service (fixes #1892)

lib/commands/arm/network/dnsZone._js, lib/commands/arm/network/expressRoute._js, lib/commands/arm/network/loadBalancer._js, lib/commands/arm/network/localNetworkGateway._js, lib/commands/arm/network/network._js, lib/commands/arm/network/nic._js, lib/commands/arm/network/nsg._js, lib/commands/arm/network/publicIp._js, lib/commands/arm/network/routeTable._js, lib/commands/arm/network/trafficManager._js, lib/commands/arm/network/virtualNetwork._js, lib/commands/arm/network/virtualNetworkGateway._js, lib/commands/arm/tag/tagUtils.js, lib/plugins.arm.json, lib/plugins.asm.json, lib/util/utils.js, test/commands/arm/network/arm-network-express-route-circuit-tests.js, test/commands/arm/network/arm.network.nic-tests.js, test/commands/arm/network/arm.network.nsg-tests.js, test/commands/arm/network/arm.network.publicip-tests.js, test/commands/arm/network/arm.network.vnet-tests.js
This PR contains improvement related to `tags` in ARM networking commands.
No need to use separate option `--no-tags` to remove tags from existing resource. Now tags can be unset in one of the following native manner:
* `-t ""`
* `-t ''`
* `-t`
=> ARM: --no-tags option removed from all networking commands

lib/commands/arm/vm/vm._js, lib/commands/arm/vm/vmExtensionProfile._js, lib/plugins.arm.json, lib/util/vmConstants.js
With this patch, enabling diagnostics with `azure vm enable-diag` without specifying a `wadcfg` file (with `--config-file`) will use a default generated `wadcfg` config file that will collect basic metrics.
You can have a preview in the attached zip file on what default wadcfg looks like on Windows and what it looks like on Linux; this is not something I invented: this is the default configuration that is set when you enable the diagnostics from the new portal. With this, you will be able to collect and see `basic metrics` and view charts from the new portal and you will be able to use Azure Insights. 
I have also updated the default Windows and Linux extension to the latest version available (Windows 1.5 and Linux 2.2).
Linux:
Windows:
Default wadcfg files: …
=> Collect basic metrics when enabling vm diagnostics

test/util/authentication/osx-keychain-parser-tests.js
The test is osx specific and not covered by CI which uses linux
=> fix osx token test issues

lib/cli.js
This is not the right code, but appears *correct *under the context that we do have [cmdlet code](https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/storage.util._js#L369) failed to clean up the progress on exception and leave azure-cli hang there. A little worse, we have no clear idea of how many those cmdlets we have. With that, I will bring back the sync version of "shutdonw"
=> cli: fall back to use process.exit

.jshintrc, lib/commands/arm/network/dnsZone._js, lib/commands/arm/network/recordSetUtils._js
Minor changes which brings output of `azure network dns record-set list` command in next level with human-friendly table format:
```
data:    Name                TTL   Type   Records                           Tags
data:    ------------------  ----  -----  --------------------------------  -----------------
data:    *                   3600  A      192.168.17.22                     tag1=hhh;tag3=ccc
data:                                     192.168.17.23
data:    @                   3600  SOA    host:    ns1-04.azure-dns.com.
data:                                     email:   hostmaster.example.com.
data:                                     refresh: 43200
data:                                     retry:   900
data:                                     expire:  1814400
data: …
```
=> ARM: 'network dns record-set list' output improved

lib/commands/arm/group/groupUtils._js
If the subscription is not defined, it results in the following error. Hence, instantiating the current subscription value before calling createClient
verbose: TypeError: Cannot read property 'resourceManagerEndpointUrl' of undefined
<<< async stack >>>
at _createArmClient (a:\newGit2\azure-xplat-cli\lib\util\utils.js:107:36)
at Object.exports.createResourceClient (a:\newGit2\azure-xplat-cli\lib\util\utils.js:262:10)
at exports_getFailedDeploymentOperations__3 (a:\newGit2\azure-xplat-cli\lib\commands\arm\group\groupUtils._js:484:20)
at __1 (a:\newGit2\azure-xplat-cli\lib\commands\arm\group\group.deployment._js:78:47)
at __1 (a:\newGit2\azure-xplat-cli\lib\commands\arm\group\group.deployment._js:67:25)
<<< raw stack >>>
at _createArmClient …
=> fix regression issue

lib/commands/arm/keyvault/keyvault.secret._js
Modified shorthand flag -s to -w in order to fix conflict in 'keyvault secret set' command.
=> Fixed shorthand flag conflict in 'keyvault secret set'

lib/cli.js, lib/commands/account._js, lib/commands/login._js, lib/util/profile/profile.js, lib/util/profile/subscription.js, lib/util/utils.js, test/util/utils-tests.js
This improved the experiences in such aspects
1. If your current subscription is backed by certificated from a publish settings file, "azure logout" will not throw with null ref, rather tell you are not really logged in 
2. If you logged in using cert, and switch to "arm",  you will get a warning with reasonable suggestion to either run "azure login" or "azure account set"
3. If you go ahead to run arm cmdlets anyway, you will get the error with similar text
4. If you logged in under asm, and switch to arm, I verified the credential should just work to run cmdlets. 
5. If you logged in successfully, azure-cli will guarantee to select one of its subscriptions. Before, it might stick to an existing unrelated subscription, which is confusing
=> fix #2529, #2530, #1913 about confusions on cred shareing between asm and arm mode

CONTRIBUTING.md
This commit fixes the broken link for the 'Microsoft Azure Projects Contribution Guidelines'
=> Fix broken link for contribution guidelines

lib/commands/arm/network/network._js, lib/commands/arm/network/trafficManager._js, lib/plugins.arm.json
*  `--resource-group` now optional for `azure network traffic-manager profile list`
@amarzavery please merge,
@jtuliani for visilivlity.
=> ARM: --resource-group now optional for 'azure network traffic-manager profile list'

lib/commands/arm/network/network._js, lib/commands/arm/network/trafficManager._js, lib/plugins.arm.json
* ARM: network `vnet/lb/publicip/nic/nsg/traffic-manager profile/express-route circuit` **list** commands now supports `--resource-group` as optional parameter for backward compatibility.
@amarzavery please merge
@jtuliani for visibility
=> ARM: Network list commands improved

lib/util/logging.js
*  CLI: improved warn output to respect --json option
Related  issue https://github.com/Azure/azure-xplat-cli/issues/2579 fixed
@yugangw-msft please review & merge
FYI: @MikhailTryakhov
=> CLI: improved warn output to respect --json option

lib/commands/arm/network/publicIp._js
* ARM: 'azure network public-ip list' command fixed to output 'IP Address' column
Related issue https://github.com/Azure/azure-xplat-cli/issues/2649 fixed
=> ARM: 'network public-ip list' now shows 'IP Address' column

lib/commands/arm/network/network._js, lib/plugins.arm.json, test/commands/arm/network/arm.network.application-gateway-tests.js
Need to merge PR [#2707](https://github.com/Azure/azure-xplat-cli/pull/2706) to revert unit test list.
Add to Changelog
- Changed short version of `--protocol` from `-t` to `-r` for `app gateway http-listener add` command
=> Reworked app gateways tests to more readable formatter using

lib/commands/arm/network/appGateway._js
Fixes #2768 - ARM: Application gateway with custom backend port
=> Parsing the strings to ints to fix errors when using custom ports

lib/util/interaction._js
Fixes #2820 by removing buffer's encoding. Not required and defaults to `utf-8`
=> Fix for buffer under node v6

lib/util/storage.util._js
* Similar to #2821, removing buffer's encoding is required to work with storage blobs under Node.js version 6.
=> Remove encoding from storage util

README.md
* The link was broken linking to the `azure-sdk-for-node` repo documentation for creating a principal
=> Fixed link for automation auth

lib/commands/arm/powerbiembedded/powerbiembedded._js
The 409 can mean either name conflict with existing workspace collection or also be returned due to the subscription not having the Microsoft.Powerbi RP registered. Removing the custom error handling and allowing the original error to be thrown will ensure proper response body / error message is displayed.
=> Remove custom 409 error handling from powerbi create command since it's not always accurate.

lib/util/logging.js
This improvement should allow to avoid constructions like `row.cell('cell', value || '');` as `''` will be substituted automatically
@amarzavery @yugangw-msft please merge
=> CLI: table output improved

lib/util/utils.js, test/framework/cli-test.js
* ability to generate random values within a command; record them if a test runs that command and retrieve them from the recording file if the test for that command is being run in playback mode
=> random value generation that is production and test playback safe

lib/commands/arm/keyvault/keyvault._js, lib/commands/arm/keyvault/keyvault.certificate._js, lib/commands/arm/keyvault/keyvault.key._js, lib/commands/arm/keyvault/keyvault.secret._js, lib/commands/arm/keyvault/kv-utils.js, lib/plugins.arm.json, lib/util/utils.js, package.json, test/commands/arm/keyvault/arm.keyvault-certificate-tests.js, test/commands/arm/keyvault/arm.keyvault-tests.js, test/testlist-arm-keyvault-live.txt
1. Move to autorest base node SDK
2. Add support for Key Vault certificates
3. Key Vault certificates tests
=> Key Vault: Add support for certificates, move to auto-rest based node SK

lib/commands/arm/vm/vm._js, lib/commands/arm/vm/vmProfile._js, lib/plugins.arm.json
Fix #2601: 'vm set' command to support '--new-os-disk-size' input
=> Fix #2601: 'vm set' command to support '--new-os-disk-size' input

test/commands/arm/iothub/arm.iothub-tests.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_create_command_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_create_iothub_key_command_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_delete_iothub_key_command_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_eventhub_consumer_group_commands_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_iothub_deletion_command_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_list_iothubs_command_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_list_keys_command_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_opmon_related_commands_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_set_sku_commands_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_stats_commands_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_update_c2d_commands_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_update_d2c_commands_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_All_Tests_update_tags_commands_should_work.nock.js, test/recordings/arm-cli-iothub-tests/suite.arm-cli-iothub-tests.nock.js
This fixes iothub tests in Live\Recording mode: Previously they took location value from previous tests (process.env setup). The location taken is not supported for iothub operations.
=> update location and recordings to fix iothub tests

package.json
- to resolve npm deprecated package warn from usage of tough-cookie@2.2.2
This resolves the last of such warnings mentioned at https://github.com/Azure/azure-xplat-cli/issues/3108 and hence closes the bug.
=> upgrade azure-common package dependency

lib/commands/arm/iothub/iothub._js, lib/plugins.arm.json, package.json, test/commands/arm/iothub/arm.iothub-tests.js, test/recordings/arm-cli-iothub-tests/arm_iothub_Connection_String_Tests_create_command_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_Connection_String_Tests_get_default_connection_string_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_Connection_String_Tests_get_specific_connection_string_should_work.nock.js, test/recordings/arm-cli-iothub-tests/arm_iothub_Connection_String_Tests_ip_filter_rules_set_and_list_command_using_files_should_work.nock.js, test/recordings/arm-cli-iothub-tests/suite.arm-cli-iothub-tests.nock.js
Added support for the following IP filter-rules commands in IotHub:
1. List IP filter rules: azure iothub ipfilter-rules list [resource-group] [name]
2. Set IP filter rules: azure iothub ipfilter-rules set [resource-group] [name] [input-file]
=> Added support for IP filtering rule commands in IotHub

lib/util/interaction.js
* Skip output of progress spinners when running with AZURE_NON_INTERACTIVE_MODE set
mostly resolves #3292
=> Skip progress indicators if running in non-interactive mode

lib/commands/arm/network/dnsZone._js, lib/commands/arm/network/zoneFile._js
* Fixed issues in PTR record set records import
* Fixed issue with ```record-set add-record``` command adding PTR type record
* Fixed issue [#3282](https://github.com/Azure/azure-xplat-cli/issues/3282) with ```record-set delete``` commands: ```type``` option is not case sensitive anymore
=> Dns zone commands hot fixes

lib/commands/arm/vm/vmClient._js
Fixes an issue where incorrect or unhelpful status was being reported for Linux volumes.  When a Linux VM is being queried this code will now pull the encryption state of OS and data volumes from the extension's instanceview substatus message field.
=> add Linux support to showAzureDiskEncryptionStatus

lib/commands/arm/network/appGateway._js, lib/commands/arm/network/network._js, lib/plugins.arm.json
* Fixed issue [#3283](https://github.com/Azure/azure-xplat-cli/issues/3283)
* Added an ability to associate app gw probe and http settings
=> Fixed issue #3283

test/commands/cli.telemetry-test.js
* update userAgent tests and remove tests for
command name and command parameters. these were moved from userAgent
info to its own separate object with PR
https://github.com/Azure/azure-xplat-cli/pull/3392 Commit (613c7d4).
This change updates the tests for userAgent object to not test for
command data.
=> update telemetry tests after changes made for 0.10.8 release

lib/commands/portal._js, lib/util/profile/profile.js
* Improvement to azure portal command.
We now try to infer the environment the user is likely to prefer, when
they omitted the -e argument to the command. With this change, if -e is
omitted, we open the portal for the environment associated with the
user's subscription that they are currently signed into. Other cases (
where -e is specified, user is not signed in etc.) remain the same as
before.
* Fixes bug #2074
=> Improvement to azure portal command.

lib/util/utilsCore.js
* Do not prompt for telemetry if AZURE_NON_INTERACTIVE_MODE environment variable is set. This behavior is intended to make scripting scenarios better. E.g: running azure cli on a CI server.
If the environment variable is not set and if we don't have a telemetry profile, we prompt, once, which is basically existing behavior.
* Fixes #3297
=> Do not prompt for telemetry if AZURE_NON_INTERACTIVE_MODE environment variable is set.

lib/util/telemetry.js, test/commands/cli.telemetry-test.js
* Added an error category field to telemetry event data that helps
classifying errors encountered broadly into two categories. Internal CLI
errors are marked as 'CLI_Error' while command service requests that
fail are identified by 'Cmdlet_Error_<HTTP_STATUSCODE>'.
* Added telemetry unit tests that verify error classification.
* Fixes #2779
=> Client side telemetry: adding error classification

lib/commands/batch/batch.pool._js
Fixed a typo in the package reference parsing in the add pool code path.
=> [BATCH-BETA] Fix typo in add pool package ref parsing

tools/windows/Product.wxs, tools/windows/azure-cli.wixproj, tools/windows/scripts/prepareRepoClone.cmd
* This change modifies the setup authoring to install 64bit NodeJs on
64bit CPUs and prefer 32bit NodeJs on 32bit CPUs. The CLI authoring
harvests the clone of source repo and deploys it to target directory. We
want to opt out of that process for authoring node.exe. We then author
the appropriate bitness node.exe based on VersionNT64 conditional check.
* Fixes #3451
=> Change setup authoring to install 32 or 64 bit Node based on target cpu arch

lib/commands/storage/storage.blob._js, lib/util/storage.util._js, package.json, test/commands/arm/group/arm.group.deployment-tests.js
* Updated azure-storage module to 2.0.0
* Supported large block blob
Besides the Changelog, we'd like to request update the ReadMe to suggest user to: 
* Use 64-bit Windows for large block blob transfer
* Install 64-bit node on 64-bit Linux machine
Please let me know if this doable.
=> Update for Storage commands

lib/commands/arm/vm/vm._js, lib/commands/arm/vm/vmClient._js
* Unblocks managed disk scenario by adding a **--skip-vm-backup** option to the enable-encryption command. 
* Tested manually since automated testing for Linux target scenario is blocked. 
* More tests to increase Linux target VM coverage are scheduled to be included prior to next release. 
* Keeps the CLI in parity with similar change submitted simultaneously to azure-powershell :
https://github.com/Azure/azure-powershell/pull/3510
=> add --skip-vm-backup option for Linux to fix #3503

lib/commands/arm/vm/vm._js, lib/commands/arm/vm/vmClient._js, lib/commands/asm/vm._js, lib/commands/asm/vm/vmclient.js, lib/plugins.asm.json
Currently `azure-xplat-cli` accepts daemon as none and service. We need to add support to accept `task` as well.
=> Add support for passing daemon as task

lib/util/telemetry.js, test/commands/cli.telemetry-test.js
* add a SHA-256 hash of macAddress to userAgent header, per VS Telemetry standard.
=> Add mac hash to user agent header

lib/commands/storage/storage.blob._js, lib/plugins.asm.json, lib/util/storage.util._js, package.json, test/commands/cli.storage.blob-tests.js
* Upgraded azure-storage to 2.1.0
* Added `--incremental` parameter to `azure storage blob copy start` command to support page blob incremental copy
=> Update Storage Commands

cli.njsproj, lib/util/cliUserAgentFilter.js, lib/util/constants.js, lib/util/utils.js, package.json, test/commands/cli.useragent-test.js
1. use xplat cli's own unique user agent filter instead of mixing with
the rdfe runtime's filter. this was the rootcause of some bugs on how it
operates alongside of ms-rest runtime's own user agent filter as the cli
relies on ms-rest runtime to make requests. xplat cli's user agent
filter now correctly puts it UserAgent header in the request.
2. update ms-rest and ms-rest-azure runtime dependency
=> update user agent logic for cli

lib/util/authentication/adalAuth.js
Doing for cloud console, that they like to redirect to /tmpfs (in memort) for better security
=> login:allow accesstokens.json to be configurable through env var

lib/commands/arm/network/dnsZone._js, lib/commands/arm/network/zoneFile._js, test/data/zone_file_export.txt, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_create_should_create_dns_zone.nock.js, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_delete_should_delete_dns_zone.nock.js, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_export_should_export_dns_zone_to_zone_file.nock.js, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_import_should_import_dns_zone_from_zone_file.nock.js, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_import_should_parse_zone_file.nock.js, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_list_should_display_all_dns_zones_in_resource_group.nock.js, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_set_should_modify_dns_zone.nock.js, test/recordings/arm-network-dns-zone-tests/arm_network_dns_zone_show_should_display_details_of_dns_zone.nock.js, test/recordings/arm-network-dns-zone-tests/suite.arm-network-dns-zone-tests.nock.js
* Added validation for record set names
* Added code to trim tokens like `[AGE:xxxxxx]` that make DNS zone list input invalid
* Improved `dns zone import` progress' output
* Re-recorded unit tests
* Network
* DNS Zone Import's data validation is improved
=> Improved Network DNS Zone Import's data validation

.travis.yml, package.json, test/testlist-arm-deployment.txt, test/testlist-arm.txt
1. Splitting test commands invoked from travis CI into arm and asm tests. While the breakdown makes sense logically, the intention behind is to shutdown and restart node process inbetween to see if this reduces the memory pressure enough to resolve the intermittent out-of-memory problems we've been observing.
1. upgrade CI environment from `Precise` to `Trusty`. This should get us VMs with 7.5G memory (See [travis-documentation](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) and [announcement](http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/))
1. pass --max_old_space_size to increase V8's default memory limit constraints. (See [this](https://github.com/nodejs/node/issues/13018), [this](https://github.com/nodejs/node/issues/10137) and …
=> Travis CI improvements

lib/util/logging.js, package.json
* Fixed bug https://github.com/Azure/azure-xplat-cli/issues/3605. The issue is that, xplat-cli fails to install with npm5. The root cause was we're using an old version of `easy-table` package that has a bug with file system permissions and was later fixed. This PR updates the version of `easy-table` to a more recent one.
=> upgrade easy table dependency

lib/util/profile/account.js, test/util/profile/account-tests.js
All tokens to access azure resource can be acquired using multi-resource-refresh-tokens, hence this filed should `true`
=> cloud console: fill in isMRRT field when being invoked with raw tokens

tools/windows/scripts/prepareRepoClone.cmd
on the build machine. however, keep the logic to download and use latest
npm around. if ever needed, swap out `npm` command with `NPMLOCAL` thats
defined by the script.
=> [Windows Installer Build Infrastructure] switch to using npm thats installed

README.md
Based on the following error, updated to use the recommended verify command. I didn't realize until I was through several of the commands that I wanted to the next step. As such, I would also recommend moving the install from npm step to be the first install step since that's what most would likely take.
$ npm cache clear -g
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carlo.wahlstedt/.npm/_logs/2017-08-02T13_23_36_247Z-debug.log
The content to be …
=> updating README for npm5 commands

lib/util/profile/account.js, test/util/profile/account-tests.js
This field is not really used by either ADAL or CLI for token refreshing. But still a bug as ADAL sets it using integer type, so we have inconsistency here.
=> cloud-shell: set 'expiresIn' with an integer value

test/framework/test-logger.js
Function `pad` in `getTimeStamp` returns value of `Number` type if that value has already been greater than 10 which may result in generation of incorrect timestamp. For example, Oct. 2, 2017 would be generated as `2017 + 10 + '02' + '_' + ...` resulting in timestamp `202702_...`.
Explicitly converting return value of `pad` to string fixes that.
=> Fixed incorrect timestamp generation

lib/util/profile/subscription.js
The account created by CLI 2.0 has main properties updated per review with the cloud shell team, so i am updating 1.0 accordingly
=> cloud shell: able to consume accounts created by CLI 2.0 in the cloud shell
