Azure/azure-xplat-cli

- lib/commands/asm/storage.account._js
- lib/commands/asm/storage.blob._js
- lib/util/storage.util._js
1. Support Premium_LRS storage account type Support --type in storage account commands
2. Warn the ACL error in XIO account and don't block container operation
> Support Premium_LRS storage account type in storage commands

- README.md
Corrected spelling of "traffic"
> Update README.md to correct misspelling

- lib/commands/asm/vm/vmclient.js
Because "ReferenceError: name is not defined"
I created PR #1502, but I mistook target branch.
> failed vm endpoint create

- lib/util/utils.js
Fix for #1593.
node_modules/azure-common/lib/services/filters/proxyfilter.js:61didn't receive key and cert in resource param.
(against the dev branch).
> Fix for https://github.com/Azure/azure-xplat-cli/issues/1593.

- tools/osx-setup/scripts/createTarball.sh
- tools/windows/scripts/prepareRepoClone.cmd
This is caused by our streamline package upgrading needed for node 0.12.0
> fix installer issues in mac and windows

- lib/cli.js
- lib/commands/account._js
- lib/commands/asm/account.cert._js
Moreover, cert based commands will not be shown in arm mode.
> A user friendly error message for cert based auth in arm mode

- lib/commands/arm/providers/provider._js
- lib/commands/asm/provider.js
- lib/util/profile/subscription.js
- lib/util/utils.js
- Made ARM mode RP registration commands public
- Brought ASM mode RP registration commands in working condition
- Re-factored provider registration logic, to make things simpler
> Optimization of RP registration

- lib/util/extendedcommand.js
Add some top level package information to the helpJSON representation.
> Enhance helpJSON with package information

- lib/commands/asm/hdinsight._js
- test/hdinsight/unit-cli-setup.js
1. Fix the bug on listCluster command which shows duplicate items
2. Fix parameter description for storageAccountName, so that user is not confused. URL is needed here.
3. Also update the test to align with the changes
> Fix 2 bugs in HDInsight CLI

- lib/commands/arm/apiapp/apiapp._js
Recent RP change broke the display of apiapp list, this is a quickie fix so we're not showing "undefined" everywhere until I can get the real fix in.
> Removing columns from apiapp list that aren't returned anymore

- README.md
- These links will never change
> updated installer links with fwlinks in README

- lib/commands/arm/webapp/webapp._js
> minor modifications in the naming.

- lib/util/utils.js
Fixing some error handling code
> CLI Mobile Undefined Response Error Fix

- lib/util/utils.js
> Fix for the hdinsight job hive_create command 

- lib/cli.js
Fix for https://github.com/Azure/azure-xplat-cli/issues/1903
> Fix broken site commands

- package.json
> Updating version number for package.json

- ChangeLog.txt
Changes to servicemanagement compute and networking described.
> Update ChangeLog.txt with changes for release 0.9.6

- lib/commands/login._js
- lib/util/profile/profile.js
- test/commands/cli.account-tests.js
- test/util/profile/profile-tests.js
fix https://github.com/Azure/azure-xplat-cli/issues/1925 and https://github.com/Azure/azure-xplat-cli/issues/1875
> Remember the default subscription during login

- lib/commands/arm/network/network._js
- lib/commands/arm/network/nic._js
- lib/plugins.arm.json
Changes:
Added support for NIC IDNS
Added support for --enable-ip-forwarding option
> Network CLI Commands: ARM NIC features

- README.md
Updating the package README with up to date Docker integration info.
> Update docker port to 2376

- lib/commands/arm/group/group._js
- lib/plugins.arm.json
fix https://github.com/Azure/azure-xplat-cli/issues/1954
> typo fix in the arm group create command

- lib/commands/arm/group/groupUtils._js
- lib/util/utils.js
- test/data/arm-deployment-template.json
I added the BOM to the "arm-deployment-template.json" for test coverage.
this fixes https://github.com/Azure/azure-xplat-cli/issues/1966
> strip BOM in a right way

- lib/commands/arm/ad/ad.application._js
Corrected the documentation that was displaying <start-date> on the <end-date> parameter.
> Correct doc on the ad application method

- lib/commands/arm/group/groupUtils._js
Remove auto-register when creating deployments
> Remove auto-register when creating deployments

- README.md
fix https://github.com/Azure/azure-xplat-cli/issues/1978
> add doc for using China cloud

- package.json
https://github.com/Azure/azure-xplat-cli/issues/1918, so a federated account can log in with password containing &
> upgrade adal-node to 0.1.15 to fix 1918

- .gitignore
- lib/util/authentication/adalAuth.js
- test/util/authentication/adalAuth-tests.js
Fix https://github.com/Azure/azure-xplat-cli/issues/1958
> fix the bug that can't use service principal in mac

- lib/util/endpointUtil.js
- lib/util/vnet.util._js
I ran into some issues creating firewall rules in Azure, so here are some fixes.
> Minor fixes to CIDR validation

- README.md
- lib/cli.js
- lib/plugins.arm.json
- lib/plugins.asm.json
- lib/util/extendedcommand.js
Fix https://github.com/Azure/azure-xplat-cli/issues/1894
> fix #1894 by documenting the usage of -vv

- lib/commands/arm/network/loadBalancer._js
- lib/commands/arm/network/nic._js
This PR contains minor fixes for `azure network nic create` command, also code formatting.
Fixed issues:
https://github.com/Azure/azure-xplat-cli/issues/2013
https://github.com/MSOpenTech/azure-xplat-cli/issues/464
https://github.com/MSOpenTech/azure-xplat-cli/issues/465
> ARM NIC: address-pool, inbound-rule parameters fixed

- lib/commands/arm/network/network._js
- lib/commands/arm/network/nic._js
- lib/commands/arm/network/routeTable._js
- lib/commands/arm/network/subnet._js
- lib/commands/arm/network/vnetShowUtil._js
This PR contains `Route Table` changes in `ARM` mode requested by @DeepakRajendranMsft
*  `network route-table route create` added validation for `next hop ip address` parameter
*  `network vnet subnet show` added output for `Route Table` reference
*  `network route-table show` added output for `Subnet` reference
Related issue fixed https://github.com/MSOpenTech/azure-xplat-cli/issues/484
> ARM: Route Table fixes

- lib/commands/arm/keyvault/keyvault.key._js
- lib/commands/arm/keyvault/keyvault.secret._js
- lib/util/profile/environment.js
- lib/util/profile/subscription.js
Remove hard coded parameter for multiple azure environment support.
> Add environment parameter for keyvault dns suffix

- lib/commands/arm/network/dnsRecordSet._js
- lib/commands/arm/network/loadBalancer._js
- lib/commands/arm/network/nic._js
- lib/commands/arm/network/trafficManager._js
- lib/commands/asm/network/appGateway._js
- lib/commands/asm/network/localNetwork._js
- lib/commands/asm/network/subnet._js
- lib/commands/asm/network/trafficManager._js
- lib/commands/asm/network/virtualNetwork._js
- lib/util/utils.js
This PR contains minor fix for `utils.indexOfCaseIgnore()` function, now it return `-1` instead of `null` when item not found. Also fixed all usages of this function.
Related issue fixed, reported here https://github.com/Azure/azure-xplat-cli/pull/2077
> Utils: indexOfCaseIgnore function improved

- lib/commands/asm/network/constants._js
- lib/commands/asm/network/nsg._js
This PR contains minor fix for `network nsg rule create` command:
* Asterisk support added
*  `INTERNET, VIRTUAL_NETWORK, AZURE_LOADBALANCER ` rule types support added
* related https://github.com/Azure/azure-xplat-cli/issues/2002 issue fixed
> ASM: NSG Rule create command fixed

- lib/commands/login._js
Spotted this when investigated a MTA login issue
> print out a more complete summary for the tenant list

- README.md
Just made it clear how to run the program from the source code.
> Readme fixes on how to run code from source

- lib/commands/arm/usage/usage._js
Clarify the format of the date parameters and prompted for the dates if they weren't provided.
> Updated help for the usage list command

- lib/commands/asm/network/virtualNetwork._js
This PR contains minor fix for `azure network vnet list` command in `ASM`, related  https://github.com/Azure/azure-xplat-cli/issues/2143 issue fixed
> ASM: network vnet list command fixed

- lib/commands/arm/network/constants._js
- lib/commands/arm/network/dnsRecordSet._js
- lib/commands/arm/network/dnsZone._js
- lib/commands/arm/network/lbShowUtil._js
- lib/commands/arm/network/loadBalancer._js
- lib/commands/arm/network/localNetworkGateway._js
- lib/commands/arm/network/network._js
- lib/commands/arm/network/nic._js
- lib/commands/arm/network/nsg._js
- lib/commands/arm/network/publicIp._js
- lib/commands/arm/network/routeTable._js
- lib/commands/arm/network/subnet._js
- lib/commands/arm/network/trafficManager._js
- lib/commands/arm/network/virtualNetwork._js
- lib/commands/arm/network/virtualNetworkGateway._js
- lib/plugins.arm.json
- package.json
This PR contains:
* `ARM` Load Balancer `Inbound NAT Pools` commands implemented, requested by @DeepakRajendranMsft and @FrankSiegemund 
* `azure-arm-network` package version updated to latest  `0.10.5`
*  Load Balancer refactoring: constants improved, checking `statusCode` instead of error message, etc.
> ARM: LoadBalancer Inbound NAT Pools implemented

- lib/commands/arm/vm/networkNic._js
- lib/commands/arm/vm/vm._js
- lib/commands/arm/vm/vmClient._js
- lib/commands/arm/vm/vmExtensionProfile._js
- lib/commands/arm/vm/vmProfile._js
- lib/commands/arm/vm/vmStorageProfile._js
- lib/commands/asm/vm._js
- lib/commands/asm/vm/vmclient.js
- lib/plugins.arm.json
- lib/plugins.asm.json
- lib/util/vmConstants.js
- Fixed bugs
- Removed support for ASM images in ARM
> Updated Compute Commands

- lib/commands/asm/network/appGateway._js
- lib/commands/asm/network/nsg._js
- lib/commands/asm/network/reservedIp._js
- lib/commands/asm/network/routeTable._js
- lib/commands/asm/network/subnet._js
- lib/commands/asm/network/vpnGateway._js
This PR contains minor code improvements in `ASM`
> ASM: check for statusCode instead of status message

- lib/commands/arm/network/expressRoute._js
- lib/commands/arm/network/network._js
- lib/plugins.arm.json
This minor PR includes `azure network express-route provider list` command implemented
> ARM: Express Route Providers list command implemented

- lib/commands/arm/network/nic._js
This PR contains **minor** fix for https://github.com/Azure/azure-xplat-cli/issues/2236 issue
Please merge asap.
> ARM: 'azure network nic inbound-nat-rule/address-pool add' command fixed

- lib/commands/arm/network/constants._js
- lib/commands/arm/network/network._js
- lib/commands/arm/network/nsg._js
- lib/commands/arm/network/trafficManager._js
- lib/commands/asm/network/subnet._js
- lib/plugins.arm.json
This PR contains minor fix for issue https://github.com/Azure/azure-xplat-cli/issues/2238 + refactoring.
Please close this PR https://github.com/Azure/azure-xplat-cli/pull/2239 as duplicate.
> ARM: 'network nsg rule create' added support for port range

- lib/commands/arm/network/lbShowUtil._js
- lib/commands/arm/network/loadBalancer._js
- lib/plugins.asm.json
Minor fix for issue https://github.com/Azure/azure-xplat-cli/issues/2262
> ARM: 'network lb frontend-ip create' command fixed

- lib/commands/asm/mobile._js
Change to synchronize portal & cli behavior for mobile service deletion
> Mobile delete logic fix

- lib/commands/arm/network/constants._js
- lib/commands/arm/network/dnsZone._js
- lib/commands/arm/network/zoneFile._js
Minor code improvements for `DNS Zone` commands in `ARM`, please merge
> ARM: DNS Zone code re-worked a little bit, more clean now

- lib/commands/asm/network/network._js
- lib/commands/asm/network/trafficManager._js
This PR contains minor fix for https://github.com/Azure/azure-xplat-cli/issues/2309 issue
> ASM: 'network traffic-manager profile endpoint create/set' Status option fixed

- lib/util/authentication/token-cache.js
- test/util/authentication/token-cache-tests.js
the goal is to fix #2269
There are several options to fix that bug, but this is the most straightforward.
> Do not persist several useless token properties

- lib/commands/arm/network/nsg._js
This PR contains minor fixes for below issues in ARM:
* https://github.com/Azure/azure-xplat-cli/issues/2319 issue fixed
* https://github.com/Azure/azure-xplat-cli/issues/2317 issue fixed
@amarzavery @yugangw-msft please merge
> ARM: 'network nsg list/show' commands updated

- lib/commands/arm/network/zoneFile._js
@amarzavery @yugangw-msft please include this small fix in 0.9.13 release branch
+@jtuliani @MikhailTryakhov  for visibility
> ARM: Zone Export output file formatting fixed

- tools/osx-setup/scripts/createTarball.sh
- tools/windows/scripts/prepareRepoClone.cmd
This shrink down the installer size by 10MB
> Installer: remove big VS profile temp data file 

- lib/commands/arm/network/zoneFile._js
https://github.com/Azure/azure-xplat-cli/issues/2366 issue fixed
> ARM: 'azure network zone export' now exports the first record of type SOA

- lib/commands/arm/network/constants._js
- lib/commands/arm/network/network._js
- lib/plugins.arm.json
ARM: tags help message moved to constants instead of duplicating everywhere in commands declaration
> ARM: tags help message moved to constants

- lib/commands/arm/network/vnetShowUtil._js
Minor fix for https://github.com/Azure/azure-xplat-cli/issues/2391 issue
> ARM: 'azure network vnet show' issue fixed

- lib/commands/arm/network/constants._js
- lib/commands/arm/network/network._js
- lib/commands/arm/network/virtualNetworkGateway._js
- lib/plugins.arm.json
Minor changes, related issue fixed https://github.com/Azure/azure-xplat-cli/issues/2414
> ARM: 'azure network vpn-gateway create/set/list' improved

- package.json
- test/commands/arm/network/arm.network.traffic-manager-tests.js
- test/recordings/arm-network-traffic-manager-endpoint-tests/arm_network_traffic-manager_endpoint_create_External_Endpoints_type_should_pass.nock.js
- test/recordings/arm-network-traffic-manager-endpoint-tests/arm_network_traffic-manager_endpoint_delete_should_delete_profile_endpoint.nock.js
- test/recordings/arm-network-traffic-manager-endpoint-tests/arm_network_traffic-manager_endpoint_set_should_modify_profile_endpoint.nock.js
- test/recordings/arm-network-traffic-manager-endpoint-tests/arm_network_traffic-manager_endpoint_show_should_display_details_of_profile_endpoint.nock.js
- test/recordings/arm-network-traffic-manager-endpoint-tests/suite.arm-network-traffic-manager-endpoint-tests.nock.js
- test/recordings/arm-network-traffic-manager-tests/arm_network_traffic-manager_profile_create_should_pass.nock.js
- test/recordings/arm-network-traffic-manager-tests/arm_network_traffic-manager_profile_delete_should_delete_traffic-manager_profile.nock.js
- test/recordings/arm-network-traffic-manager-tests/arm_network_traffic-manager_profile_is-dns-available_checks_specified_DNS_prefix_is_available_for_creating_traffic-manager_profile.nock.js
- test/recordings/arm-network-traffic-manager-tests/arm_network_traffic-manager_profile_list_should_get_all_traffic-manager_profiles_from_resource_group.nock.js
- test/recordings/arm-network-traffic-manager-tests/arm_network_traffic-manager_profile_set_should_modify_traffic-manager_profile.nock.js
- test/recordings/arm-network-traffic-manager-tests/arm_network_traffic-manager_profile_show_should_display_details_of_traffic-manager_profile.nock.js
- test/recordings/arm-network-traffic-manager-tests/suite.arm-network-traffic-manager-tests.nock.js
Minor changes related to traffic-manager in ARM: package version updated to **0.10.5**
@amarzavery @yugangw-msft please merge
For visibility: @jtuliani
> ARM: azure-arm-TrafficManager package updated, nocks updated

- lib/commands/login._js
- lib/plugins.arm.json
- lib/plugins.asm.json
- lib/util/authentication/adalAuthForServicePrincipal.js
- test/util/profile/account-tests.js
> enable login using a service principal with a certificate

- lib/commands/arm/network/network._js
- lib/commands/arm/network/virtualNetworkGateway._js
- lib/plugins.arm.json
Minor change, related issue fixed https://github.com/Azure/azure-xplat-cli/issues/2443
@yugangw-msft @amarzavery please merge
> ARM: added ability to create connection between Gateways in different resource groups

- lib/commands/arm/network/nic._js
- lib/commands/arm/network/virtualNetwork._js
* Minor PR to fix `regression` issue reported here https://github.com/Azure/azure-xplat-cli/issues/2436 
* Small typo in `vnet show` fixed
@yugangw-msft please merge
> ARM: 'nic create' fixed issue with --public-ip-name

- lib/commands/config.js
- lib/util/logging.js
so far, w/o the change, command output/logging such as "azure config list --json" does not work
> cmdlets: get config commands use common execution flow

- scripts/unit.js
- test/testlistarmlive.txt
1. Display start and end time
2. Trim line breaks so external test file can load
> test: some preparation for live test run

- package.json
Upgrade azure-storage NodeJS NPM module from 0.6.0 to 0.7.0
> Upgrade azure-storage NodeJS NPM module from 0.6.0 to 0.7.0

- lib/commands/arm/vm/vmClient._js
- lib/commands/arm/vm/vmExtensionProfile._js
- lib/commands/arm/vm/vmStorageProfile._js
- lib/commands/storage/storage.account._js
- lib/util/utils.js
- package.json
- test/commands/arm/datalakeanalytics/arm.datalake-analytics-tests.js
- test/commands/arm/storage/arm.storage.account-tests.js
[storage] switch to the swagger based REST client lib
> [storage] switch to the swagger based REST client lib

- lib/commands/arm/network/nic._js
One-line fix for `azure network nic create` in ARM
@yugangw-msft @amarzavery please merge
> ARM: nic create small fix

- test/commands/arm/network/arm.network.vpn-connection-tests.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_create_first_gateway_should_pass.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_create_second_gateway_and_create_gateway_connection_should_pass.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_delete_should_delete_gateway_connection.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_list_should_display_all_gateway_connections_in_a_given_resource_group.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_set_should_modify_gateway_connection.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_shared-key_set_should_modify_gateway_connection_shared_key_value.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_shared-key_show_should_should_display_gateway_connection_shared_key_value.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_show_should_display_details_of_gateway_connection.nock.js
- test/recordings/arm-network-vpn-connection-tests/suite.arm-network-vpn-connection-tests.nock.js
- test/util/util.js
Minor fix for 'network vpn-connection delete' test case to run against live server
> ARM network: 'vpn-connection delete' test updated

- test/commands/arm/network/arm.network.vpn-connection-tests.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_create_first_gateway_should_pass.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_create_second_gateway_and_create_gateway_connection_should_pass.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_delete_should_delete_gateway_connection.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_list_should_display_all_gateway_connections_in_a_given_resource_group.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_set_should_modify_gateway_connection.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_shared-key_set_should_modify_gateway_connection_shared_key_value.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_shared-key_show_should_should_display_gateway_connection_shared_key_value.nock.js
- test/recordings/arm-network-vpn-connection-tests/arm_network_vpn-connection_show_should_display_details_of_gateway_connection.nock.js
- test/recordings/arm-network-vpn-connection-tests/suite.arm-network-vpn-connection-tests.nock.js
- test/util/util.js
- merging Roman's PR #2488 in to the release-0.9.15 branch
> Release 0.9.15

- lib/commands/arm/network/recordSetUtils._js
Related issue fixed https://github.com/Azure/azure-xplat-cli/issues/2493
Still getting CI issue reported here https://github.com/Azure/azure-xplat-cli/issues/2489
please merge @amarzavery @yugangw-msft
> ARM: 'azure network dns record-set list' now outputs empty record sets

- scripts/harvest-cmds.js
The script will leverage metedata json in the repository
> fix havesting script bugs and do not require azure-cli to be preinstalled

- lib/commands/arm/group/groupUtils._js
> fixes #2518

- lib/commands/arm/group/group.deployment._js
Fixes https://github.com/Azure/azure-xplat-cli/issues/2486
> adding correlationId in display

- lib/commands/arm/rediscache/rediscache._js
- lib/plugins.arm.json
- test/commands/arm/rediscache/arm.rediscache-tests.js
Adding set-diagnostics command to redis cache cli
> Adding set-diagnostics command to redis cache cli

- lib/commands/asm/network/appGateway._js
Removed extra-parameter from API method call
> Resolved issue https://github.com/Azure/azure-xplat-cli/issues/2575

- ChangeLog.md
- lib/commands/arm/ad/ad.application._js
- tools/windows/Product.wxs
*  updated the changelog
*  updated product.wxs
*  sneaking in a small fix
> updates for release-0.9.16

- package.json
- test/recordings/arm-cli-vm-usage-tests/arm_compute_vm_should_list_usage_correctly.nock.js
- test/recordings/arm-cli-vm-usage-tests/suite.arm-cli-vm-usage-tests.nock.js
- test/testlist-arm-vm-live.txt
- test/testlist-arm-vm.txt
Update VM Usage Test Record (Fix #2588)
> 	Update VM Usage Test Record (Fix #2588)

- lib/util/profile/account.js
- test/util/profile/account-tests.js
fix #2602 that you can't login using government account
> Use resource management endpoint associated with current environment (us azure, government)

- lib/commands/arm/network/expressRoute._js
- test/commands/arm/network/arm.network.express-route-authorization-tests.js
- test/recordings/arm-network-express-route-authorization-tests/arm_network_express-route_authorization_create_should_pass.nock.js
- test/recordings/arm-network-express-route-authorization-tests/arm_network_express-route_authorization_delete_should_delete_express-route_authorization.nock.js
- test/recordings/arm-network-express-route-authorization-tests/arm_network_express-route_authorization_list_should_display_all_express-routes_authorization_from_resource_group.nock.js
- test/recordings/arm-network-express-route-authorization-tests/arm_network_express-route_authorization_set_should_modify_express-route_authorization.nock.js
- test/recordings/arm-network-express-route-authorization-tests/arm_network_express-route_authorization_show_should_display_details_of_express-route_authorization.nock.js
- test/recordings/arm-network-express-route-authorization-tests/suite.arm-network-express-route-authorization-tests.nock.js
Removed extra-error message when authorization item was not found
> Reworked ARM express route auth tests

- lib/commands/arm/providers/provider._js
> Fixes issue #2619

- lib/commands/arm/network/expressRoute._js
Fix for #2667 
* Remove incorrect properties of provider
> Fix incorrect properties of provider in the listProviders method

- ChangeLog.md
- package.json
- tools/windows/Product.wxs
> Release 0.9.19 updates

- lib/commands/arm/group/group.template._js
- lib/commands/arm/group/groupUtils._js
* Throw error when template validate fails
> Fix template validate when response has error

- lib/commands/asm/service._js
- test/recordings/cli.service-tests/cli_service_server_cmdlets_List_and_show_Cloud_Service_should_show_the_service.nock.js
- test/recordings/cli.vm.create_affin_vnet_vm-tests/cli_vm_Create_should_delete_cloud_service_on_vm_create_failure.nock.js
> Fixes issue #2274

- lib/util/telemetry.js
- lib/util/utilsCore.js
- test/framework/cli-test.js
> Updated telemetry

- lib/commands/arm/vm/vmClient._js
- lib/util/vmConstants.js
> Adding fix to use the default key encryption algorithm if not specified

- lib/commands/arm/vm/vmClient._js
> Fixing default algorithm for key encryption key

- test/commands/arm/network/arm.network.express-route-authorization-tests.js
- test/recordings/arm-network-express-route-authorization-tests/arm_network_express-route_authorization_create_should_pass.nock.js
- test/util/networkTestUtil.js
> Reworked express route auth to common readable style

- lib/commands/arm/datalakeanalytics/datalakeanalytics._js
this change just ensures that the values passed in by the user are turned into integers.
> force priority and degree of parallelism to be ints

- lib/commands/arm/cdnmanagement/cdnmanagement._js
- lib/commands/arm/policy/policy.assignment._js
- lib/commands/arm/policy/policy.definition._js
- lib/commands/arm/vm/vm._js
- lib/commands/arm/vm/vmOsProfile._js
- lib/plugins.arm.json
- test/commands/arm/cdnMangement/arm.cdnMangement-tests.js
> fix prompt for adminPassword if ssh key file is provided

- README.md
> add CDN in readme

- Dockerfile
- README.md
> Release 0.9.20

- lib/commands/arm/webapp/webapp._js
- lib/plugins.arm.json
*  revert 'enclosed required args in angular brackets for webapp command help'
*  added help usage for webapp commands
*  regenerated help-plugins.
> Regenerated help usage for webapp commands

- lib/commands/arm/group/group._js
- lib/commands/arm/group/group.deployment._js
* Prettify json output before writing to file for RG export and deployment save commands
> Prettify json output before writing to file for RG export and deployment save commands

- package.json
* updated storage to 0.13.1-preview
> updated storage to 0.13.1-preview

- package.json
> update package version to include new enum.

- lib/commands/asm/network.generated/network._js
- lib/plugins.asm.json
> Update help for azure network *-migration

- lib/commands/arm/network/constants._js
- lib/commands/arm/network/loadBalancer._js
- lib/commands/arm/network/localNetworkGateway._js
- lib/commands/arm/network/network._js
- lib/commands/arm/network/nsg._js
- lib/commands/arm/network/routeTable._js
- lib/commands/arm/network/subnet._js
- lib/commands/arm/network/virtualNetworkGateway._js
- lib/plugins.arm.json
- lib/util/utils.js
- lib/util/validation.js
Code base minor improvement.
@amarzavery please merge
> ARM: moved some networking stuff to new validation logic

- lib/commands/arm/vm/vmExtensionProfile._js
> Update vm enable-diag command to use JSON config for Linux.

- lib/commands/storage/storage.blob._js
- lib/plugins.arm.json
- lib/plugins.asm.json
Improve the option description in `azure storage blob delete`
> Improve the option description

- ChangeLog.md
- package.json
- tools/windows/Product.wxs
> Bump up version to 0.10.1 and updated changelog for Release 0.10.1

- lib/commands/batch/batch.account._js
> Fix bug in batch account update command.

- README.md
Adding Batch to the feature list on the README page.
> Add Batch to README

- lib/util/utilsCore.js
> The CLI will not prompt for telemetry if telemetry command is the first command to be used

- lib/commands/arm/network/zoneFile._js
* Resolved issues importing record set in case when record name is equal to any record type
> Resolved issue with dns zone record sets import 

- lib/commands/arm/compute/virtualMachineScaleSetVMs._js
- lib/commands/arm/compute/virtualMachineScaleSets._js
- lib/plugins.arm.json
- lib/plugins.asm.json
- package.json
> Cplat PR -- Update new Compute package

- lib/commands/arm/vm/vmClient._js
* Changed show vm functionalirt: throw error instead of warning if incorrect name of VM was entered
> Resolved issue with ARM VM Show method

- lib/commands/arm/vm/virtualMachine._js
> Fix VM List/ListAll #2961

- package.json
> Bumped up adal-node version to 0.1.21

- lib/commands/arm/compute/virtualMachineScaleSets._js
- lib/plugins.arm.json
- test/commands/arm/vmss/arm.vmss-create-tests.js
- test/commands/arm/vmss/arm.vmss-parameter-create-tests.js
* Fix vmss list & remove list-all
> Azure CPlat - Fix vmss list & remove list-all

- lib/commands/arm/network/dnsZone._js
* Added extra-validator for record set location (set default if it's empty)
> Fixed issue with ID 6762945.

- lib/commands/arm/devtestlabs/devTestLabs._js
*  Fixed devTestLabs module import issue.
* 
*
> fixed a module missing issue on Linux

- Dockerfile
*  Updated Dockerfile to use latest source for nightly build. https://github.com/Azure/azure-xplat-cli/issues/2915
* 
*
> docker build use latest source

- lib/commands/asm/hdinsight._js
- lib/plugins.asm.json
> fixes 3003

- lib/commands/arm/group/group._js
> fixes 2938

- lib/commands/storage/storage.account._js
> fixes #2966

- lib/util/interaction.js
> fixes #1847 #3015

- lib/commands/login._js
* Fixed issue https://github.com/Azure/azure-xplat-cli/issues/3027
* 
*
> Fixed a service principal login issue

- lib/commands/arm/vm/networkPublicIP._js
> fixes #3013

- lib/commands/asm/site.repository._js
- package.json
> fixes #1794

- lib/commands/arm/network/dnsZone._js
* Added workaround for old azure-arm-dns package location issue
> Added workaround to prevent issue with location required parameter

- lib/util/telemetry.js
* setting cert thumbprint as the userId while sending telemetry, if the user is using cert based auth for rdfe commands
> Telemetry Update

- lib/commands/arm/usage/usage._js
> fixes #2117

- lib/plugins.arm.json
> generated plugins

- ChangeLog.md
- package.json
- tools/windows/Product.wxs
* update version and changelog to 0.10.3
* 
*
> update version and changelog

- package.json
* updating azure-common to 0.9.17
> updating azure-common to 0.9.17

- lib/util/profile/profile.js
* Changed azureProfile file permission to 600
> Changed azureProfile file permission to 600

- README.md
> Update docs for auto-complete

- lib/commands/login._js
> Validate username option for service principal login

- README.md
- lib/util/utilsCore.js
- package.json
> use user-home lib in replace of HOME discover function

- lib/commands/help.js
* Improved the help command experience
> Improved the help command experience

- lib/commands/asm/vm/vmclient.js
* [ASM] Fix VM Password Interactive Input Issue #3106
> [ASM] Fix VM Password Interactive Input Issue #3106

- lib/commands/login._js
- lib/plugins.arm.json
- lib/util/authentication/adalAuth.js
* disable validate authority for AzureStack
> disable validate authority

- test/data/imageUrn.json
> Fix Image URN for VM Related Tests

- lib/commands/arm/vm/vm._js
- test/data/imageUrn.json
@amarzavery @haocs Please help review. Thanks.
> Fix https://github.com/Azure/azure-xplat-cli/issues/3119 & VM image URN

- lib/commands/arm/providers/provider.operations._js
* https://github.com/Azure/azure-xplat-cli/issues/3023
* 
*
> Added check for null/undefined

- lib/commands/arm/vm/vm._js
- lib/commands/arm/vm/vmClient._js
- lib/commands/arm/vm/vmShowUtil._js
- lib/plugins.arm.json
- lib/plugins.asm.json
- test/commands/arm/vm/arm.vm-quick-create-tests.js
- test/data/customdata.txt
- test/recordings/arm-cli-vm-quick-create-tests/arm_compute_vm_quick_create_with_existing_group_should_pass.nock.js
- test/recordings/arm-cli-vm-quick-create-tests/arm_compute_vm_quick_create_with_non-existing_group_should_pass.nock.js
- test/recordings/arm-cli-vm-quick-create-tests/arm_compute_vm_redeploy_vm_should_pass.nock.js
- test/recordings/arm-cli-vm-quick-create-tests/suite.arm-cli-vm-quick-create-tests.nock.js
> Fix #3118: Add '-w, --public-ip-domain-name' to 'azure vm quick-create'

- ChangeLog.md
> Release 0.10.4

- lib/plugins.arm.json
- lib/plugins.asm.json
* fix typographic errors in help files
> Fix typos in help files

- lib/commands/arm/resource/resourceUtils.js
* Ignore resource group case when validating source and destination group in resource move
> Ignore source resource groups case when validating resource move

- lib/commands/arm/datalakestore/datalakestore._js
This allows for the import of an empty file into ADLS.
> Fix issue: https://github.com/Azure/azure-xplat-cli/issues/3163

- package.json
- test/commands/cli.storage.account-tests.js
- test/recordings/arm-cli-batch-application-tests/arm_batch_application_should_create_applications_package_within_the_application.nock.js
* Upgraded the azure-storage dependency to 1.3.0 to address the tough-cookie security issue
> Update for Storage commands

- lib/util/telemetry.js
> Added back ip for telemetry

- ChangeLog.md
- lib/commands/serviceFabric._js
- lib/commands/serviceFabric/serviceFabricApplication._js
- lib/commands/serviceFabric/serviceFabricCluster._js
- lib/commands/serviceFabric/serviceFabricNode._js
- lib/commands/serviceFabric/serviceFabricPackage._js
- lib/commands/serviceFabric/serviceFabricPartition._js
- lib/commands/serviceFabric/serviceFabricReplica._js
- lib/commands/serviceFabric/serviceFabricService._js
- lib/commands/serviceFabric/serviceFabricServiceGroup._js
- lib/commands/serviceFabric/serviceFabricUtils._js
- lib/plugins.arm.json
- lib/plugins.asm.json
- package.json
- tools/windows/Product.wxs
* updated changelog
* moved serviceFabric to its own folder
> Release 0.10.5

- lib/commands/arm/datalakestore/datalakestore._js
we support both text and binary files on xplat, this was an old not from development.
> Remove erroneous note.

- lib/commands/arm/network/network._js
- lib/commands/arm/network/virtualNetworkPeerings._js
- lib/plugins.arm.json
This PR adds required parameters to the usage string and allows to use required parameters as positional w/o using `--<option-name>`
> Extract required parameters to positional

- lib/commands/arm/hdinsight/hdinsight._js
* Fix logClusterOperationInfo to log both operation status and state
> Fix logClusterOperationInfo to log both operation status and state

- lib/commands/arm/network/network._js
- lib/commands/arm/network/virtualNetworkGateway._js
- lib/plugins.arm.json
- lib/plugins.asm.json
* Fixed issue https://github.com/Azure/azure-xplat-cli/issues/2804
> Fixed issue with Express Route VPN connection

- Documentation/Writing-Cmd.md
- lib/commands/arm/webapp/webapp.config._js
- lib/plugins.arm.json
- package.json
> Integrate from dev to 0.10.6

- lib/commands/arm/group/group._js
- lib/commands/arm/group/group.deployment._js
- test/commands/arm/group/arm.group.deployment-tests.js
Throw error when deployment fails
> Throw error when deployment fails

- lib/commands/arm/network/virtualNetworkGateway._js
> Fixed peer info messages

- lib/commands/arm/network/dnsZone._js
* Fixed issue https://github.com/Azure/azure-xplat-cli/issues/3242
> Fixed issue in DNS info message

- lib/commands/arm/keyvault/keyvault.certificate._js
- lib/plugins.arm.json
- package.json
- test/commands/arm/keyvault/arm.keyvault-certificate-tests.js
* 'keyvault certificate policy create' is supporting --certificate-type argument.
> Adding certificateType and renaming issuerReference

- lib/commands/arm/vm/vmProfile._js
@amarzavery @haocs Could you please help review? Thanks.
> Fix #3248 on VM command's end.

- .travis.yml
- lib/commands/arm/ad/ad.groups._js
- lib/commands/arm/ad/ad.servicePrincipals._js
- lib/commands/arm/ad/ad.users._js
- lib/commands/arm/ad/adUtils._js
- lib/commands/arm/network/nsg._js
- lib/commands/arm/usage/usage._js
- lib/plugins.arm.json
- lib/plugins.asm.json
- lib/util/logging.js
- lib/util/utils.js
- package.json
- test/commands/arm/datalakestore/arm.datalake-store-tests.js
- test/commands/arm/usage/arm.usage.feature-tests.js
- test/recordings/arm-cli-usage-tests/suite.arm-cli-usage-tests.nock.js
* Usage
* Ported azure-arm-commerce to use Autorest based library
* Provided support for `| more` while paging
* fixes #3239 and #3255.
* ActiveDirectory
* Fixed the implementation of `| more` while paging in `azure ad sp|user|group|group memeber list` commands
> upgraded user experience of usage list command

- lib/commands/arm/network/network._js
- lib/plugins.arm.json
- lib/plugins.asm.json
* corrected inconsistent option naming in app gateways backend-health command
> Fixed issue https://github.com/Azure/azure-xplat-cli/issues/3295

- lib/commands/arm/vm/vmImage._js
* Fix typographical error in user message for get VM images.
> fix "verions" to "versions"

- README.md
> update command to uninstall the CLI

- lib/commands/servicefabric/serviceFabricPackage._js
* app package copy to use persist connection
> Service fabric

- Documentation/SetupBatchTest.md
- lib/commands/batch/batch.templateUtils._js
- Remove public storage container references
> [Batch-beta] Update URLs to be github based

- lib/commands/arm/network/appGateway._js
- lib/commands/arm/network/constants._js
- lib/commands/arm/network/network._js
- lib/plugins.arm.json
- test/commands/arm/network/arm.network.application-gateway-tests.js
- test/recordings/arm-network-application-gateway-tests/arm_network_application-gateway_create_again_should_pass.nock.js
* Fixed issue [#3339](https://github.com/Azure/azure-xplat-cli/issues/3339)
* Added an ability to change default names for app gateway http-settings, http listener, frontend port, frontend ip, gateway IP config
* Fixed extra-logger and mistypes in commands
> Arm app gw create commands improved

- bin/azure.js
- cli.njsproj
- lib/util/telemetry.js
- lib/util/userAgentCore.js
- lib/util/utils.js
- test/commands/cli.telemetry-test.js
* Add OS info and command info to user agent string.
* Refactored code around telemetry.
* Added tests for the new scenarios.
> Add OS and command diagnostics in User agent header

- .jshintrc
- lib/commands/batch/batch.templateUtils._js
- package.json
- test/commands/batch/cli.batch.template-parsing-tests.js
- test/testlist-batch.txt
* Unit testing and associated fixes for batch template expansion
> [batch-beta-dev] Feature/batch template testing

- lib/commands/arm/network/appGateway._js
* Fixed issue https://github.com/Azure/azure-xplat-cli/issues/3354
> Removed ssl cert param from app gw show command when listener protocol is http

- lib/commands/arm/network/appGateway._js
> Reworked url path map listing

- lib/commands/arm/group/group.deployment._js
> Change deployment polling logic.

- lib/commands/arm/network/appGateway._js
* Fixed issue https://github.com/Azure/azure-xplat-cli/issues/3353
> Reworked app gateways rule list command

- lib/commands/arm/network/dnsZone._js
- lib/commands/arm/network/recordSetUtils._js
- lib/commands/arm/network/zoneFile._js
* Fixed issue https://github.com/Azure/azure-xplat-cli/issues/2869
> Fixed DNS zone import issue with semicolon symbol

- lib/commands/arm/datalakeanalytics/datalakeanalytics._js
- lib/plugins.arm.json
> One missed usage definition match for ADL

- ChangeLog.md
- package.json
- tools/windows/Product.wxs
> changes for 0.10.8 release

- Documentation/BatchDocumentation/shipyard.md
* Update Batch Shipyard integration to version 2.2.0
> [batch-beta-dev]: Update Batch Shipyard integration to version 2.2.0

- lib/util/commandMetadataFilter.js
- lib/util/constants.js
- lib/util/telemetry.js
- lib/util/userAgentCore.js
- lib/util/utils.js
- package.json
* Updated applicationInsights dependency to 0.17.1 from 0.15.2
* Added support for x-ms-command-name, x-ms-parameterset-name and modified the content of "user-agent" header
> Release 0.10.8

- lib/cli.js
* Improve error message about command not being valid.
Hint that it could be a valid command in the other mode (asm/arm).
* Fixes bugs #3272, #3256
> Improve cli error message for commands not valid under current mode.

- lib/commands/batch/batch.fileUtils._js
Cache resolved storage account
> [batch-beta-dev] Performance improvement

- lib/commands/arm/network/dnsZone._js
- lib/commands/arm/network/recordSetUtils._js
- lib/commands/arm/network/zoneFile._js
- lib/util/logging.js
* Fixed TXT records output format
> Dev dns import hot fix

- appveyor.yml
Initiate the appveyor.yml file towards master branch to pull and process content to content repo.
> set appveyor

- Documentation/BatchDocumentation/samples/docker/job.docker.caffe.json
- Documentation/BatchDocumentation/samples/docker/pool.docker.caffe.json
- Documentation/BatchDocumentation/samples/docker/readme.md
Add a readme for the Batch Shipyard integration sample.
> [batch-beta-dev]: Add readme for Batch Shipyard sample

- ChangeLog.md
- package.json
- tools/windows/Product.wxs
> changes for 0.10.9 release

- appveyor.yml
> Update access token to docs repo

- lib/commands/arm/vm/vm._js
- test/commands/arm/vm/arm.vm-quick-create-tests.js
* update the plugin file missed in earlier commit
* improve tests to cover scenario better
> regenerate plugins.arm.json for quick-create params

- README.md
- package.json
* Add auto completion for fish shell
> Update omelette for fish shell's completion

- ChangeLog.md
- package.json
- tools/windows/Product.wxs
updating package versions and changelog.
> changes for release-0.10.10

- package.json
- test/commands/cli-auto-complete.tests.js
- test/commands/cli.site.deploymentscript-tests.js
- test/commands/cli.telemetry-test.js
- test/commands/cli.vm.create_comm-tests.js
- test/commands/cli.vm.create_staticvm-tests.js
- test/framework/cli-executor.js
- test/framework/cli-test.js
- test/framework/fake-files.js
- test/util/authentication/adalAuth-tests.js
- test/util/interaction-tests.js
* fix sinon.stub as per the new signature
> fix sinon.stub as per the new signature

- cli.njsproj
- lib/util/utils.js
- test/commands/cli.useragent-test.js
- test/commands/cli.useragentfilter-test.js
remove the sdk signature added with previous PR and add more tests to user agent filter
> Update User Agent string and add tests

- lib/commands/arm/vm/vm._js
> Fix help text for 'azure vm image show' #3548

- lib/util/storage.util._js
* Added support for large page blob (8TB)
> Added support for large page blob (8TB)

- lib/util/telemetry.js
- lib/util/userAgentCore.js
- test/commands/cli.telemetry-test.js
* Remove cli mode, userId hash and subscriptionId hash from the user agent string based on guidance from ARM team.
* Fixes #3565 
* updates tests
> Standardize UA string in request header

- ChangeLog.md
- package.json
- tools/windows/Product.wxs
* updating product version and change log for release-0.10.13
> Preparing for release 0.10.13

- lib/commands/asm/compute/virtualMachine._js
- lib/plugins.asm.json
- test/commands/cli.vm.initiate-maintenance-tests.js
- test/recordings/cli.vm.initiate-maintenance-tests/suite.cli.vm.initiate-maintenance-tests.nock.js
> Add ASM Compute VM Commands: Delete/Redeploy/Start/Restart/GetRDP/Show

- tools/windows/scripts/prepareRepoClone.cmd
.. a recent stable version of npm. The script downloads npm 4.6.0 and
unzips it to a temp location and uses it. This ensures our node_modules
folder is deduped. Ensuring we're on a recent stable version of npm
prevents bugs like #3624 which arise because dependency management
software (npm in this case) wasn't updated in a while.
> [Build Infrastructure] Update windows build script to use..

- tools/nix-setup/build.sh
- tools/windows/scripts/prepareRepoClone.cmd
See Node security update for July: https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
> upgrade node version to 6.11.1 to take security updates

- ChangeLog.md
- package-lock.json
- package.json
- tools/windows/Product.wxs
> release-0.10.17

- ChangeLog.md
- package-lock.json
- package.json
- tools/windows/Product.wxs
> updates releasing artifacts for 0.10.18

- lib/commands/asm/network/network._js
- lib/commands/asm/network/reservedIp._js
- lib/plugins.asm.json
- package-lock.json
* Added associate/deassociate commands to ASM reserved IP
> Added associate/deassociate commands to ASM reserved IP, improved reserved-ip create command

- README.md
Deprecate this project explicitly.
> Update README to deprecate this project explicitly
